<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Elixir</title>

    <link rel="stylesheet" href="dist/reset.css">
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/dracula.css">

    <!-- Theme used for syntax highlighted code -->
    <link rel="stylesheet" href="plugin/highlight/monokai.css">
</head>

<body>
    <div class="reveal">
        <div class="slides">
            <section style="background-color: white; border-radius: 1rem;">
                <img width="400"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Official_Elixir_logo.png/800px-Official_Elixir_logo.png" />
                <h3>Scalable, Fault-Tolerant, Functional</h3>
            </section>

            <section>
                <h3>Designed by</h3>
                <img width="400" src="https://2023.elixirconf.com/images/presenters/jose-valim.jpg" />
                <h5>JosÃ© Valim</h5>
            </section>

            <section>
                <h2>Why was Elixir Created?</h2>
                <ul>
                    <li>JosÃ© Valim made Elixir because:</li>
                    <ul>
                        <li>Ruby (MRI) threads are not real threads</li>
                        <li>Ruby on Rails thread safety is hard to keep</li>
                        <li>He heard about what we can do with Erlang</li>
                    </ul>
                </ul>
                <ul>
                    <li>Development:</li>
                    <ul>
                        <li>Started in 2010</li>
                        <li>Version 1.0 released in 2014</li>
                    </ul>
                </ul>
            </section>

            <section>
                <h3>Comparison ?</h3>
                <img width="900"
                    src="https://i.ytimg.com/vi/AN9y0k8Hy9o/maxresdefault.jpg" />
            </section>
            <section>
                    <h3>
JS can be functional, whereas Elixir is (always) Functional!
                    </h3>
            </section>
           <section>
                <h3>Definition</h3>
                <p><strong>Fault:</strong> A defect or error in the software.</p>
                <p><strong>Failure:</strong> The observable incorrect behavior caused by the fault.</p>
            </section>

            <section>
                <h3>Example 1: Bug in Code</h3>
                <p><strong>Fault:</strong> Incorrect discount calculation (e.g., division by zero).</p>
                <p><strong>Failure:</strong> The application crashes when a user applies a discount.</p>
            </section>

            <section>
                <h3>Example 2: Memory Leak</h3>
                <p><strong>Fault:</strong> Memory is not released properly.</p>
                <p><strong>Failure:</strong> The application slows down and eventually crashes.</p>
            </section>

            <section>
                <h2>Elixir process world</h2>
                <img width="700" src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*Mqxgq6aE9dYOKhIxz_3Gdg.jpeg"/> </section>
            </section>

            <section>
                <h2>Demo: Process</h2>
                <img width="400"
                    src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGZzNm45ZWJyZHJhaDBpZXQ1M2FhdHFhdWFyeXM2Y3gzYXdkNXlieSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/4JGsvG6bDPAfMc45ID/giphy.gif" />
            </section>

            <section>
                <h3><strong>OOP?</strong> Will Crash on Error</h3>
                    <h4>Handle exception with <strong>(try-catch)</strong> block</h4>
                <pre><code data-trim data-noescape data-trim data-noescape>
                class SumCalculator
                  def calc_sum(n)
                    raise "error" if n == 13
                    (1..n).sum
                  end
                end

                calc = SumCalculator.new

                begin
                  puts calc.calc_sum(10)  # Output: 55
                  puts calc.calc_sum(13)  # Error, but program continues
                rescue => e
                  puts "Caught error: #{e}"  # Handles error manually
                end
                    </code></pre>
            </section>


            <section>
                <h2>"Worker"</h2>
                <pre><code data-trim data-noescape data-trim data-noescape>
                    defmodule OrderProcessor do
                      use GenServer

                      def start_link(order) do
                        GenServer.start_link(__MODULE__, order, name: via_tuple(order))
                      end

                      defp via_tuple(order), do: {:via, Registry, {OrderRegistry, order}}

                      def init("bad order"), do: raise("ðŸ’¥ Order failed!")

                      def init(order) do
                        IO.puts("âœ… Order processed successfully: #{order}")
                        {:ok, order}
                      end
                    end
                </code></pre>
            </section>

            <section>
                <h2>"Supervisor"</h2>
                <pre><code data-trim data-noescape data-trim data-noescape>
                    defmodule OrderSupervisor do
                      use DynamicSupervisor

                      def start_link(_arg) do
                        DynamicSupervisor.start_link(__MODULE__, [], name: __MODULE__)
                      end

                      @impl true
                      def init(_arg) do
                        DynamicSupervisor.init(strategy: :one_for_one)
                      end

                      def start_order(order) do
                        DynamicSupervisor.start_child(__MODULE__, {OrderProcessor, order})
                      end
                    end
                </code></pre>
            </section>

            <section>
                <h2>"Test"</h2>
                <pre><code data-trim data-noescape data-trim data-noescape>
                    children = [
                      {DynamicSupervisor, name: OrderSupervisor, strategy: :one_for_one},
                      {Registry, keys: :unique, name: OrderRegistry}
                    ]

                    Supervisor.start_link(children, strategy: :one_for_one)
                    OrderSupervisor.start_order("good order")
                    OrderSupervisor.start_order("bad order")  # This crashes but won't affect other processes
                    OrderSupervisor.start_order("another good order")
                </code></pre>
            </section>

            <section>
                <h4>Normal - Supervisor tree</h4>
                <img width="500" src="image/order_sup_tree_normal.png" style="background-color: white;"/>
            </section>

            <section>
                <h4>Crash - Supervisor tree</h4>
                <img width="500" src="image/order_sup_tree_crashed.png" style="background-color: white;"/>
            </section>

            <section>
                <h4>Restart - Supervisor tree</h4>
                <img width="500" src="image/order_sup_tree_normal.png" style="background-color: white;"/>
            </section>

            <section>
                <h4>Order - "Let it crash"</h4>
                <img width="600" src="image/order_let_it_crash.png" style="background-color: white;"/>
            </section>

            <section>
                <h2>restartson for one</h2>
                <img width="700"
                    src="https://raw.githubusercontent.com/pierrelegall/erlang-elixir-presentation/refs/heads/master/images/supervisor-restartson-for-one.png" />
            </section>

            <section>
                <h2>Demo</h2>
                <img width="400"
                    src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGZzNm45ZWJyZHJhaDBpZXQ1M2FhdHFhdWFyeXM2Y3gzYXdkNXlieSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/4JGsvG6bDPAfMc45ID/giphy.gif" />
            </section>

            <section>
                <h3><strong>Fail fast, let it crash</strong></h3>
                <h4>a software development principle advocating for immediate error reporting and system termination (or "crash") rather than attempting to continue execution in an invalid state</h4>
                <img width="200"
                    src="https://media1.tenor.com/m/OT9Am8Bg9-cAAAAd/haerin-newjeans.gif" />
            </section>

            <section>
                <h2>Summary</h2>
                <ul>
                    <li>Functional, immutable, concurrent, fault-tolerant</li>
                    <li>Runs on BEAM, great for scalability</li>
                </ul>
            </section>

            <section>
                <img width="400"
                    src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGZzNm45ZWJyZHJhaDBpZXQ1M2FhdHFhdWFyeXM2Y3gzYXdkNXlieSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/4JGsvG6bDPAfMc45ID/giphy.gif" />
                <h2>QA</h2>
            </section>

            <section>
                <h2>exit(0)</h2>
            </section>
        </div>
    </div>

    <script src="dist/reveal.js"></script>
    <script src="plugin/notes/notes.js"></script>
    <script src="plugin/markdown/markdown.js"></script>
    <script src="plugin/highlight/highlight.js"></script>
    <script>
        // More info about initialization & config:
        // - https://revealjs.com/initialization/
        // - https://revealjs.com/config/
        Reveal.initialize({
            hash: true,

            // Learn about plugins: https://revealjs.com/plugins/
            plugins: [RevealMarkdown, RevealHighlight, RevealNotes]
        });
    </script>
</body>

</html>
